### ISSUE TITLE
use logging instead of printing to System.{err,out}

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#6]
The base class already configures logging, but `printStackTrace` and `System.err`/`System.out` are still used (e.g. Base, Args, Convert, Types, Writers, ....)

**Comment by tomlurge** [comment]
I added switches to send output either to the shell or to the log if logging is enabled (option -g). But the real problem is that metrics-lib doesn't support logging very well and therefor the shell output is indespensable for debugging. I would not have bothered with this issue if I hadn't forgotten that in the meantime.
When metrics-lib adds better logging support I'll try to also add support for logging levels. Until then I think it doesn't make much sense to put more effort in this issue.

**Comment by iwakeh** [comment]
metrics-lib is aiming to provide logging (slf4j) in release 1.4.0

**Comment by tomlurge** [comment]
Added comment to issue #4 to take it up again when metrics-lib is improved. Closing this issue.
